spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_management?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    #druid数据源专有配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
  redis:
    database: 0
    host: 192.168.1.6
    port: 6379
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.koko.entity
  configuration:
    map-underscore-to-camel-case: true

config:
  #JWT加密密钥(Base64加密)
  encryptJWTKey: U0JBUElOENhspJrzkyNjQ1NA
  #AccessToken过期时间 5分钟 5*60
  accessTokenExpireTime: 300
  #RefreshToken过期时间 30分钟 30*60
  refreshTokenExpireTime: 1800
  #Shiro缓存过期时间 5分钟 5*60
  shiroCacheExpireTime: 300
