package com.koko.dao;

import com.koko.entity.UserSubject;
import com.koko.entity.UserSubjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserSubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_subject
     *
     * @mbg.generated Fri May 29 10:17:26 CST 2020
     */
    long countByExample(UserSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_subject
     *
     * @mbg.generated Fri May 29 10:17:26 CST 2020
     */
    int deleteByExample(UserSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_subject
     *
     * @mbg.generated Fri May 29 10:17:26 CST 2020
     */
    int insert(UserSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_subject
     *
     * @mbg.generated Fri May 29 10:17:26 CST 2020
     */
    int insertSelective(UserSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_subject
     *
     * @mbg.generated Fri May 29 10:17:26 CST 2020
     */
    List<UserSubject> selectByExampleWithRowbounds(UserSubjectExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_subject
     *
     * @mbg.generated Fri May 29 10:17:26 CST 2020
     */
    List<UserSubject> selectByExample(UserSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_subject
     *
     * @mbg.generated Fri May 29 10:17:26 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserSubject record, @Param("example") UserSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_subject
     *
     * @mbg.generated Fri May 29 10:17:26 CST 2020
     */
    int updateByExample(@Param("record") UserSubject record, @Param("example") UserSubjectExample example);
}