package com.koko.entity;

public class Grade {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.username
     *
     * @mbg.generated Fri May 29 10:17:26 CST 2020
     */
    private Integer username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.subject_id
     *
     * @mbg.generated Fri May 29 10:17:26 CST 2020
     */
    private Integer subjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.score
     *
     * @mbg.generated Fri May 29 10:17:26 CST 2020
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.username
     *
     * @return the value of grade.username
     *
     * @mbg.generated Fri May 29 10:17:26 CST 2020
     */
    public Integer getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.username
     *
     * @param username the value for grade.username
     *
     * @mbg.generated Fri May 29 10:17:26 CST 2020
     */
    public void setUsername(Integer username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.subject_id
     *
     * @return the value of grade.subject_id
     *
     * @mbg.generated Fri May 29 10:17:26 CST 2020
     */
    public Integer getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.subject_id
     *
     * @param subjectId the value for grade.subject_id
     *
     * @mbg.generated Fri May 29 10:17:26 CST 2020
     */
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.score
     *
     * @return the value of grade.score
     *
     * @mbg.generated Fri May 29 10:17:26 CST 2020
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.score
     *
     * @param score the value for grade.score
     *
     * @mbg.generated Fri May 29 10:17:26 CST 2020
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}