package com.koko.entity;

public class UserRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.username
     *
     * @mbg.generated Fri May 29 10:17:26 CST 2020
     */
    private Integer username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.role_id
     *
     * @mbg.generated Fri May 29 10:17:26 CST 2020
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.username
     *
     * @return the value of user_role.username
     *
     * @mbg.generated Fri May 29 10:17:26 CST 2020
     */
    public Integer getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.username
     *
     * @param username the value for user_role.username
     *
     * @mbg.generated Fri May 29 10:17:26 CST 2020
     */
    public void setUsername(Integer username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.role_id
     *
     * @return the value of user_role.role_id
     *
     * @mbg.generated Fri May 29 10:17:26 CST 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.role_id
     *
     * @param roleId the value for user_role.role_id
     *
     * @mbg.generated Fri May 29 10:17:26 CST 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}